import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/global/navigation/NavBar";
import MswInitializer from "@/components/global/MswInitializer";
import { FavoritesInitializer } from "@/components/global/favorit/FavoritesInitializer";
import AuthGuard from "@/components/global/navigation/AuthGuard";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="da">
      <head>
        <link rel="apple-touch-icon" sizes="180x180" href="favicon/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="favicon/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="favicon/favicon-16x16.png" />
        <link rel="manifest" href="favicon/site.webmanifest" />
        <link rel="shortcut icon" href="favicon/favicon.ico" />
      </head>
      <body>
        <MswInitializer>
          <AuthGuard>
            <FavoritesInitializer />
            <div id="app-shell">
              <main className="flex flex-col mb-20 px-8 pt-8">{children}</main>
              <NavBar />
            </div>
          </AuthGuard>
        </MswInitializer>
      </body>
    </html>
  );
}
